<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\OrbeB2B.AutoAtendimento.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\OrbeB2B.AutoAtendimento.Infrastructure.csproj" />
  </ItemGroup>

</Project>
